[2024-05-22 02:35:32,977] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data manual__2024-05-22T02:35:31.551757+00:00 [queued]>
[2024-05-22 02:35:32,998] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data manual__2024-05-22T02:35:31.551757+00:00 [queued]>
[2024-05-22 02:35:32,999] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:35:32,999] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:35:33,000] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:35:33,020] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-22 02:35:31.551757+00:00
[2024-05-22 02:35:33,029] {standard_task_runner.py:52} INFO - Started process 3069 to run task
[2024-05-22 02:35:33,034] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'manual__2024-05-22T02:35:31.551757+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpsrmgz2v6', '--error-file', '/tmp/tmpyi9x6bwc']
[2024-05-22 02:35:33,044] {standard_task_runner.py:77} INFO - Job 31: Subtask fetch_data
[2024-05-22 02:35:33,128] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data manual__2024-05-22T02:35:31.551757+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:35:33,208] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-22T02:35:31.551757+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-22T02:35:31.551757+00:00
[2024-05-22 02:35:33,211] {logging_mixin.py:109} INFO -  url is https://api.purpleair.com/v1/sensors?fields%3D=latitude%252C%2520longitude%252C%2520humidity%252C%2520pm2.5_60minute%252C%2520last_seen
[2024-05-22 02:35:33,214] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields%3D=latitude%252C%2520longitude%252C%2520humidity%252C%2520pm2.5_60minute%252C%2520last_seen
[2024-05-22 02:35:33,215] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 02:35:33,273] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 02:35:33,274] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716345333,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 02:35:33,508] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:35:33,509] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:35:33,526] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240522T023531, start_date=20240522T023532, end_date=20240522T023533
[2024-05-22 02:35:33,568] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:35:33,611] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
