[2024-05-22 04:17:56,319] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-22T03:00:00+00:00 [queued]>
[2024-05-22 04:17:56,396] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-22T03:00:00+00:00 [queued]>
[2024-05-22 04:17:56,399] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:56,400] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:56,401] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:56,473] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-22 03:00:00+00:00
[2024-05-22 04:17:56,494] {standard_task_runner.py:52} INFO - Started process 389 to run task
[2024-05-22 04:17:56,551] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-22T03:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpit3u3o5d', '--error-file', '/tmp/tmp0dr_njs_']
[2024-05-22 04:17:56,693] {standard_task_runner.py:77} INFO - Job 44: Subtask fetch_data
[2024-05-22 04:17:56,986] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-22T03:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:57,264] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-22T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-22T03:00:00+00:00
[2024-05-22 04:17:57,269] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:57,295] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:57,295] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:57,426] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:57,427] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351477,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:57,518] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:57,519] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:57,574] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240522T030000, start_date=20240522T041756, end_date=20240522T041757
[2024-05-22 04:17:57,661] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:57,762] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
