[2024-05-22 02:20:40,254] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T21:00:00+00:00 [queued]>
[2024-05-22 02:20:40,569] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T21:00:00+00:00 [queued]>
[2024-05-22 02:20:40,576] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:40,584] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:40,599] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:40,873] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 21:00:00+00:00
[2024-05-22 02:20:40,998] {standard_task_runner.py:52} INFO - Started process 2406 to run task
[2024-05-22 02:20:41,073] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T21:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpxxzk9khu', '--error-file', '/tmp/tmppcffpp9f']
[2024-05-22 02:20:41,233] {standard_task_runner.py:77} INFO - Job 23: Subtask fetch_data
[2024-05-22 02:20:42,251] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T21:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:43,012] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T21:00:00+00:00
[2024-05-22 02:20:43,245] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:43,249] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:43,321] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T210000, start_date=20240522T022040, end_date=20240522T022043
[2024-05-22 02:20:43,447] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:43,834] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:55,088] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T21:00:00+00:00 [queued]>
[2024-05-22 04:17:55,179] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T21:00:00+00:00 [queued]>
[2024-05-22 04:17:55,198] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:55,199] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:55,200] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:55,293] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 21:00:00+00:00
[2024-05-22 04:17:55,337] {standard_task_runner.py:52} INFO - Started process 386 to run task
[2024-05-22 04:17:55,380] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T21:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpxn_9kj2e', '--error-file', '/tmp/tmp1lpcx4ac']
[2024-05-22 04:17:55,423] {standard_task_runner.py:77} INFO - Job 41: Subtask fetch_data
[2024-05-22 04:17:55,707] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T21:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:55,999] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T21:00:00+00:00
[2024-05-22 04:17:56,012] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:56,030] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:56,041] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:56,157] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:56,158] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351476,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:56,257] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:56,258] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:56,297] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T210000, start_date=20240522T041755, end_date=20240522T041756
[2024-05-22 04:17:56,394] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:56,467] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
